### ISSUE TITLE
Backport for Eloquent and Dashing

### ISSUE THREAD

**Issue by ralph-lange** [ros2/rclc#14]
The current master branch can be built against Foxy only as it uses rcl's new rcl_wait_set_is_valid()-function, which has been introduced on 2 December 2019. As this function is a one-liner only, cf. https://github.com/ros2/rcl/blob/master/rcl/src/rcl/wait.c#L83, it may be put easily into some wait_set_utils.h/.c file.

**Comment by JanStaschulat** [comment]
fixed in https://github.com/ros2/rclc/pull/17
