### ISSUE TITLE
Foxy: backport of QoS API should be removed in rclc_parameters

### ISSUE THREAD

**Issue by JanStaschulat** [ros2/rclc#140]
The backported PR https://github.com/ros2/rclc/commit/f246f1accf6a3e6ea22ff4ffb8f0f229f635694b
created a file in rclc_parameter package, even though the rclc_parameter package is not available in Foxy:
https://github.com/ros2/rclc/tree/foxy/rclc_parameter/src/rclc_parameter
(it now just contains one file)

I propose to delete the created file in `rclc_parameter` directory. 

@pablogs9 we have to be more careful with backporting to Foxy as some features are not available there. Could you check if this backport created some other incompatabilities on Foxy?

**Comment by pablogs9** [comment]
Sorry for that.
