### ISSUE TITLE
Support for clients and services in the rclc_executor

### ISSUE THREAD

**Issue by ralph-lange** [ros2/rclc#15]
Add support for clients and services to the rclc_executor, in the style of rclc_executor_add_subscription (cf. https://github.com/ros2/rclc/blob/master/rclc/include/rclc/executor.h#L208).

**Comment by jayhou** [comment]
> Add support for clients and services to the rclc_executor, in the style of rclc_executor_add_subscription (cf. https://github.com/ros2/rclc/blob/master/rclc/include/rclc/executor.h#L208).

Is there any plan to support client and service in rclc_executor?

**Comment by ralph-lange** [comment]
Yes. My colleague @JanStaschulat is already working on this in the branch https://github.com/micro-ROS/rclc/tree/feature/support_for_service_clients.

**Comment by jayhou** [comment]
> Yes. My colleague @JanStaschulat is already working on this in the branch https://github.com/micro-ROS/rclc/tree/feature/support_for_service_clients.

thanks, so great!

**Comment by JanStaschulat** [comment]
Services, clients and guard conditions were added in PR https://github.com/ros2/rclc/pull/26
