### ISSUE TITLE
rclc_executor_trigger_one way out of date

### ISSUE THREAD

**Issue by BrettRD** [ros2/rclc#153]
I'm working https://github.com/ros2/rclc/issues/116 and I'm not sure what to do with `rclc_executor_trigger_one`.

This looks like it's supposed to return `true` if at least one of `handles` is ready to be executed, but it returns `false` if it reaches a `type` in `CLIENT`, `SERVICE`, or `GUARD_CONDITION`

For now I'm expanding it to any `type` where `data_available` is ever set to `true`

If anyone knows what this is, can we discuss a test for it?

**Comment by JanStaschulat** [comment]
Yes, you can do it like that. 
Initially, we only supported subscriptions and timers for this trigger condition.
