### ISSUE TITLE
Create Bloom Release for Rolling v3.0.4

### ISSUE THREAD

**Issue by JanStaschulat** [ros2/rclc#208]
Make new rolling bloom release
depending PR:
- [x] Actions https://github.com/ros2/rclc/pull/170

TODO:
- [x] update changelog : PR https://github.com/ros2/rclc/pull/214
- [x] create tag 3.0.4
- [x] PR rosdistr:  https://github.com/ros/rosdistro/pull/31247
- [x] create repo release tag 3.0.4: https://github.com/ros2/rclc/releases/tag/3.0.4

**Comment by JanStaschulat** [comment]
development of multi-threaded executor PR will take some time. 
I will prepare for a bloom release, as the RCLC Actions PR is through.

**Comment by JanStaschulat** [comment]
created PR on rosdistro: https://github.com/ros/rosdistro/pull/31247

**Comment by JanStaschulat** [comment]
created a release tag on repository: https://github.com/ros2/rclc/releases/tag/3.0.4

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/micro-ros-fully-supports-ros-2-features/23213/1
