### ISSUE TITLE
rclc fails to initialize a support object

### ISSUE THREAD

**Issue by Salsus2191** [ros2/rclc#260]
## Issue template

- Hardware description: Arduino Nano Rp2040
- RTOS: 
- Installation type: 
- Version or commit hash:  galactic v2.0.3

#### Steps to reproduce the issue
```
void setup()
{
    Serial.begin(115200);
    set_microros_transports();
   
    
   
    Serial.print("Running\n");
    digitalWrite(LED_BUILTIN, LOW);
    allocator = rcl_get_default_allocator();
    Serial.print("Done allocating\n");
    
    rc = rclc_support_init(&support, 0, NULL, &allocator);
    if (rc != RCL_RET_OK)
    {
        Serial.print("Could not initialize node support\n");
        Serial.print(rc);
        Serial.print("\n");
        error_loop();
    }

```

#### Expected behavior
The code above should initialize the rclc_support_t 
#### Actual behavior
The init function fails and return error code 1
#### Additional information
The additional print statements are there to check where the code fails. It's used on an Arduino with micro ros arduino.

**Comment by pablogs9** [comment]
Hello, please reopen this issue in the micro-ROS for Arduino repository and explain your hardware configuration, transport, etc.

**Comment by pablogs9** [comment]
Closed in favor of https://github.com/micro-ROS/micro_ros_arduino/issues/804
