### ISSUE TITLE
RCCHECK

### ISSUE THREAD

**Issue by norro** [ros2/rclc#33]
Suggestion:
Make the current `RCCHECK` macro(s) (see [here](https://github.com/ros2/rclc/blob/6e45370f4bb5434e5bd81974829795284604cf4b/rclc_examples/src/example_client_node.c#L24-LL27) for example) part of rclc library, e.g., as `RCCHECK`/`RCLCCHECK`/`RCLC_CHECK` macro.

Rationale:
I end up introducing the same code again and again in almost all of my rclc files as well.

**Comment by norro** [comment]
@JanStaschulat what do you think?

**Comment by JanStaschulat** [comment]
Sure, you can add the macro in rclc/include/rclc/types.h like this [macro](https://github.com/micro-ROS/rclc/blob/b8ef4a6c96f3c80f1fbfd23e8127e3948d44d011/rclc/include/rclc/types.h#L42).

**Comment by JanStaschulat** [comment]
Please create PR to micro-ros/rclc.

**Comment by JanStaschulat** [comment]
Add also the error message in RCCHECK RCSOFTCHECK, like [here](https://github.com/micro-ROS/nuttx_apps/blob/8f2e0f6bfccc0d249deb730a36f17da1cb49b006/examples/uros_rbs/main_rbs.c#L33)

**Comment by norro** [comment]
Closing as per discussion here: https://github.com/micro-ROS/rclc/pull/66
