### ISSUE TITLE
Requesting release of rclc in Rolling and Humble

### ISSUE THREAD

**Issue by cottsay** [ros2/rclc#344]
Hi, it's been a while since this package has been released. #314 was merged about 2 months ago and was backported to humble. I'm normally not so invested in getting fixes like this released, but we're trying to roll out a change on the buildfarm that will break this package without that fix, which I'd prefer not to do.

A release in Rolling and Humble would be appreciated.

TODO-List (added by @JanStaschulat )
- [x] prepare release (update changelog, package.xml, tag) in Humble
- [x] release in Humble 4.0.2
- [x] prepare release (update changelog, package.xml, tag) in Rolling
- [ ] release in Rolling 3.0.9

**Comment by pablogs9** [comment]
Can you take a look @JanStaschulat ?

**Comment by JanStaschulat** [comment]
Bloom release PR:
- Humble: https://github.com/ros/rosdistro/pull/36563
- Rolling: https://github.com/ros/rosdistro/pull/36564

**Comment by JanStaschulat** [comment]
Re-run bloom-release for Rolling https://github.com/ros/rosdistro/pull/36620
