### ISSUE TITLE
Rolling, Iron, master branch out-of-sync

### ISSUE THREAD

**Issue by JanStaschulat** [ros2/rclc#369]
@pablogs9 @Acuadros95 

For some unclear reason, the `master`, `rolling`, and `iron` branch are out-of-sync, when I use the github compare function:

comparison rolling - master
https://github.com/ros2/rclc/compare/rolling...master

comparison iron - rolling
https://github.com/ros2/rclc/compare/iron...master

comparison iron - rolling
https://github.com/ros2/rclc/compare/rolling...iron

However, I compared with kdiff3 manually the entire repository (I cloned rclc twice and switched to different branches):
- master vs rolling
- master vs iron
- iron vs rolling

and they are perfectly the same. The only difference is  `ci.yml` regarding the branch-, CI-, and distribution- names. Which is okay. So my understanding is. all the branches are in-sync but the Github compare function reports 3 commit differences...
I think, we should have a clean setup before creating an iron release. 
Any ideas, how to fix this?

**A brute-force and simple solution would be:**
- Delete `iron` and `rolling` branch and copy them over from `master` again?

**Comment by pablogs9** [comment]
Indeed, they are separated: 

![image](https://github.com/ros2/rclc/assets/7647884/644a2a7c-7580-4928-aef9-f36c2c1f92f6)


Feel free to force-push them to the correct commit, as far as I understand right now they shall be pointing to the same commit right?

**Comment by JanStaschulat** [comment]
They should not point to the same commit, because the `ci.yml` is different. For each branch the ci uses different branch names, aka rolling for rolling branch, iron for iron branch, and so on. So they are not identical any more. 

But regarding the entire source code and the last two pull requests (rclc_parameter, rclc ) they are indeed the same.

**Comment by JanStaschulat** [comment]
@pablogs9 . You meant to force push the `master` branch to `rolling`and `iron` branch like this?

```
$git checkout master
$git push origin --force master:rolling
```
