### ISSUE TITLE
Service call is processed twice

### ISSUE THREAD

**Issue by norro** [ros2/rclc#40]
In an rclc application of mine, but also in the example service node (when applying [this fix](https://github.com/ros2/rclc/issues/39#issuecomment-768215233)), I see that the service is processed twice. I do not have the appropriate rcl(c) knowledge / debugging abilities to understand the source of this issue.

**Steps to reproduce:**
1. Apply [this fix](https://github.com/ros2/rclc/issues/39#issuecomment-768215233) to the example service node 
1. Execute the example service node 
1. Call the service once, e.g., with `ros2 service call /addtwoints example_interfaces/srv/AddTwoInts "{a: 17, b: 42}"`

**Expected output** of the example service node:
```
Service request value: 17 + 42
```

**Observed output** of the example service node:
```
Service request value: 17 + 42
Service request value: 17 + 42
```

**Comment by norro** [comment]
Can no longer reproduce with current rclc master.

**Comment by karl-schulz** [comment]
For anyone seeing this issue: I had a similar behavior when I accidentally attached two identical services to a node. RCL doesn't warn about this and just calls the service callback twice.
