### ISSUE TITLE
[lifecycle] Support lifecycle nodes

### ISSUE THREAD

**Issue by JanStaschulat** [ros2/rclc#56]
Add support for rclc lifecycle nodes, i.e., bundle ROS 2 default state machine with nodes, enable transition callbacks, etc.

See issue https://github.com/micro-ROS/rclc/issues/37
see also: https://github.com/micro-ROS/rclc/issues/75

**Comment by norro** [comment]
Lifecycle node included in rolling and galactic. Closed with micro-ROS#37
